### ISSUE TITLE
Improvements suggestion

### ISSUE THREAD

**Issue by qboileau** [tabmo/circe-validation#5]
## global
- Update to scala `2.12.6` if possible
- Add usage exemples in `README.md` (custom rules creation, use of predefined and custom rules on a custom decoder)  

## extra-rules
- Move / re-work `extra-rules/src/main/scala/io.tabmo.circe.extra.rules/Test.scala` file into actual test package 
- Define date rules in `DateRules` from a static `DateTimeFormat` instead of a `String` to not re-instantiate a new `DateTimeFormat` each time a rule is apply.
- Missing tests for `DateRules`

**Comment by kevin-margueritte** [comment]
All suggestions have been implemented
